"""CLI for Dakota's on-demand real historical data.

Examples:
    python -m scripts.fetch_real_history --ticker CDSL --exchange NSE --days 90
    python -m scripts.fetch_real_history --ticker AEGISLOG --exchange BSE --days 90
    python -m scripts.fetch_real_history --ticker CDSL --exchange NSE --days 90 --index

The default is intentionally small enough to validate a source before scaling.
No synthetic data is ever generated by this command.
"""
from __future__ import annotations

import argparse
from datetime import date, timedelta
import json

from src.market.real_history import (
    fetch_bse_history,
    fetch_nifty50_history,
    fetch_nse_history,
)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Fetch real NSE/BSE history for one Dakota investigation ticker."
    )
    p.add_argument("--ticker", required=True, help="Stock ticker, e.g. CDSL")
    p.add_argument(
        "--exchange",
        choices=["NSE", "BSE"],
        required=True,
        help="Exchange to fetch",
    )
    p.add_argument(
        "--days",
        type=int,
        default=90,
        help="Calendar-day window ending today (default: 90)",
    )
    p.add_argument(
        "--index",
        action="store_true",
        help="Also fetch NIFTY 50 history for the same date window (NSE only).",
    )
    p.add_argument(
        "--end",
        default=None,
        help="End date YYYY-MM-DD. Defaults to today.",
    )
    return p


def main() -> None:
    args = build_parser().parse_args()

    if args.days < 5 or args.days > 365:
        raise SystemExit("--days must be between 5 and 365")

    end_date = (
        date.fromisoformat(args.end)
        if args.end
        else date.today()
    )
    start_date = end_date - timedelta(days=args.days)

    print("=" * 64)
    print("DAKOTA REAL HISTORICAL DATA")
    print("=" * 64)
    print(f"Ticker:    {args.ticker.upper()}")
    print(f"Exchange:  {args.exchange}")
    print(f"Window:    {start_date} -> {end_date}")
    print()

    if args.exchange == "NSE":
        result = fetch_nse_history(
            args.ticker,
            start_date,
            end_date,
        )
    else:
        result = fetch_bse_history(
            args.ticker,
            start_date,
            end_date,
        )

    print(json.dumps(result.to_dict(), indent=2))

    if args.index:
        if args.exchange != "NSE":
            print("\nNIFTY 50 skipped: --index currently applies to NSE runs only.")
        else:
            print("\nNIFTY 50:")
            print(json.dumps(
                fetch_nifty50_history(start_date, end_date),
                indent=2,
            ))

    if result.status != "ok":
        raise SystemExit(1)

    print("\nREAL HISTORY FETCH PASSED")


if __name__ == "__main__":
    main()
